language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-29
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

notifications:
  email:
    on_success: never
    on_failure: always

before_script:
  - echo yes | android update sdk -u -a -t tools
  - echo yes | android update sdk -u -a -t build-tools-28.0.3
  - echo yes | android update sdk -u -a -t android-29

cache:
  directories:
    - $HOME/.gradle

script:
  - chmod +x ./gradlew
